model:
  model_type: 'gpt2'
  seed: 42

train:
  model_type: 'gpt2'
  dataset_name: 'Beauty'
  batch_size: 256
  max_length: 1024
  n_epochs: 10
  seed: 42
  max_grad_norm: 10.0
  device: 'cuda:0'
  optimizer: 'RMSprop'
  lr: 0.0001
  warmup_steps: 150
  gradient_accumulation_steps: 128
  eval_every: 15360
  save_path: './checkpoint' 